version: "3.9"

networks:
  default:
    driver: bridge
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  fastapi_app:
    build: .
    container_name: fastapi_app
    env_file:
      - ../.env  
    restart: always
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    depends_on:
      - redis